name: Build and Release ChatControl for Velocity and Purpur with GraalVM 24

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup GraalVM 24
      uses: actions/setup-java@v4
      with:
        distribution: 'graalvm'
        java-version: '24'
        cache: maven

    - name: Build all modules with Maven
      run: mvn clean package --no-transfer-progress

    - name: Gather JAR files
      run: |
        mkdir jars
        cp chatcontrol-bukkit/target/*.jar jars/
        cp chatcontrol-velocity/target/*.jar jars/

    - name: Create or update GitHub release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.sha }}
        name: Release for commit ${{ github.sha }}
        body: Release automatically created by GitHub Actions.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload JAR files to Release
      uses: softprops/action-gh-release@v2
      with:
        files: jars/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
